; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = nucleo_f767zi

[env:native]
platform = native
test_framework = doctest
lib_deps = doctest/doctest@^2.4.11
test_ignore = test_embedded

[env:nucleo_f767zi]
platform = ststm32
board = nucleo_f767zi
framework = mbed
test_framework = doctest
extra_scripts = pre:gen_compile_commands.py
lib_deps = doctest/doctest@^2.4.11
test_ignore = test_native
test_build_src = false
